export {default as Nav} from './Nav'
export {default as Banner} from './Banner'
export {default as FAQ} from './FAQ'
export {default as Footer} from './Footer'
export {default as Article} from './Article'
export {default as Header} from './Header'
export {books} from './data'